### ISSUE TITLE
I can send or write command, but cannot read data from Serial Port?

### ISSUE THREAD

**Issue by dasaintgray** [FengChendian/serial_port_win32#25] opened 2023-05-26 06:06 UTC

**Comment by Sunshine88888** [comment] 2023-06-02 09:10
Have same issue too. I believe there is something blocking read from port. When running Putty, I can see the messages written and response by program. 
Did you find a solution @dasaintgray ?

**Comment by FengChendian** [comment] 2023-06-02 11:54
Are you sure that the data stream isn't disturbed by other code?

**Comment by FengChendian** [comment] 2023-06-02 11:56
> Have same issue too. I believe there is something blocking read from port. When running Putty, I can see the messages written and response by program. 
> Did you find a solution @dasaintgray ?

Can you give me a small project which can reproduce the bug?

**Comment by Sunshine88888** [comment] 2023-06-02 14:09
Hi @FengChendian , thank you for reaching out. 
This is only project I have running with single page of code. Trying to verify the read/write function before I expand. 

I am a flutter noob so my coding structure isnt perfect. 
I use getPorts() to find specific modem I need to connect to. Open COM port to then either send a specific AT command with button or type a AT command. 
I can never see response. When I close port/program down and switch to Putty, I can see AT command sent and its response with OK at end.
I have have tried to use writeModemCommand() with/without async but still no difference. I have tried to use same code on different devices with same result. I have put some basic widgets in to monitor.
This is my code:

```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:serial_port_win32/serial_port_win32.dart';

ValueNotifier<String> definedPort = ValueNotifier("");
ValueNotifier<String> modemConnection = ValueNotifier("");
ValueNotifier<String> modemResponse = ValueNotifier("");
ValueNotifier<String> modemCommand = ValueNotifier("");
ValueNotifier<String> applog = ValueNotifier("");
ValueNotifier<int> readStatus = ValueNotifier(0);

String portName = '';
final telitPort = SerialPort(
  definedPort.value, //COM11
  ByteSize: 8,
  StopBits: 1,
  Parity: 0,
  ReadIntervalTimeout: 1,
  ReadTotalTimeoutConstant: 2,
  openNow: false,
);

final ports = SerialPort.getPortsWithFullMessages();

void getPorts() {
  final ports = SerialPort.getPortsWithFullMessages();

  for (var a = 0; a < ports.length; a++) {
    // find in string the telit modem harwareID
    String dataStr = ports[a].toString();
    int pos = dataStr.indexOf("VID_1BC7&PID_0036&MI_00");
    if (pos == -1) {
      // print("Modem COM port not found. Try unplugging/plugging modem");
    } else {
      /// find the com port number required to connect to modem
      String strData = ports[a].toString();
      print(strData);
      int start = strData.indexOf(" ", 5);
      int end = strData.indexOf(",");
      String portNo = strData.substring(start + 1, end);

      definedPort.value = portNo;
      print(definedPort.value);
    }
  }
}

Future<void> writeModemCommand(String command) async {
  try {
    telitPort.open();
    telitPort.writeBytesFromString("$command\r");

    print("Written command: $command");
    telitPort.readBytesOnListen(8, (value) async {
      String data = await String.fromCharCodes(value);
      print("${DateTime.now()} : $data");
      print(data);
    });
  } finally {}
}

void main() {
  print("Start");
  getPorts();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Modem App',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Telit Modem Status'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final txtATcommand = TextEditingController();

  void initState() {}

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Modem',
      home: Scaffold(
        appBar: AppBar(),
        body: Row(
          children: [
            Expanded(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                mainAxisSize: MainAxisSize.max,
                children: [
                  Spacer(
                    flex: 1,
                  ),
                  Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      ValueListenableBuilder(
                          valueListenable: definedPort,
                          builder: (context, value, child) {
                            return Text("Modem Port: ${definedPort.value}");
                          }),
                      ValueListenableBuilder(
                          valueListenable: modemConnection,
                          builder: (context, value, child) {
                            return Text("Connection to Modem: ${modemConnection.value}");
                          }),
                      ValueListenableBuilder(
                          valueListenable: modemCommand,
                          builder: (context, value, child) {
                            return Text("Command: ${modemCommand.value}");
                          }),
                      ValueListenableBuilder(
                          valueListenable: modemResponse,
                          builder: (context, value, child) {
                            return Text("Response: ${modemResponse.value}");
                          }),
                    ],
                  ),
                  Spacer(
                    flex: 1,
                  ),
                ],
              ),
            ),
            Expanded(
              child: Column(
                children: [
                  Spacer(
                    flex: 1,
                  ),
                  TextField(
                    controller: txtATcommand,
                    decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      hintText: 'Enter AT command',
                    ),
                    onSubmitted: (value) => writeModemCommand(txtATcommand.text),
                  ),
                  Spacer(
                    flex: 1,
                  ),
                  ElevatedButton(
                    child: Text('Send AT'),
                    onPressed: () => {
                      // Replace with your desired modem command
                      writeModemCommand("AT"),
                    },
                  ),
                  Spacer(
                    flex: 1,
                  ),
                  ElevatedButton(
                    child: Text('Get Network Status'),
                    onPressed: () => {
                      // Replace with your desired modem command
                      writeModemCommand("AT+CREG?"),
                    },
                  ),
                  Spacer(
                    flex: 1,
                  ),
                  ElevatedButton(
                    child: Text('Get Phone No.'),
                    onPressed: () => {
                      // Replace with your desired modem command
                      writeModemCommand("AT+CNUM"),
                    },
                  ),
                  Spacer(
                    flex: 1,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
Snip of Putty:
![image](https://github.com/FengChendian/serial_port_win32/assets/34958458/598bf161-6e49-4bed-b0c6-0e78cc19950b)

Snip from USBDeview:
![image](https://github.com/FengChendian/serial_port_win32/assets/34958458/72874106-09f2-4ee7-b0d8-e8c3510fb56d)

**Comment by FengChendian** [comment] 2023-06-02 16:38
> 

I will test your code tomorrow. But intuitively I think your code may be causing some problems.

In SerialPort, I use singleton mode like:
```dart
return _cache.putIfAbsent(
    portName,
    () => SerialPort._internal(
          portName,
          TEXT('\\\\.\\$portName'),
          BaudRate: BaudRate,
          Parity: Parity,
          StopBits: StopBits,
          ByteSize: ByteSize,
          ReadIntervalTimeout: ReadIntervalTimeout,
          ReadTotalTimeoutConstant: ReadTotalTimeoutConstant,
          ReadTotalTimeoutMultiplier: ReadTotalTimeoutMultiplier,
          openNow: openNow,
        ));
```

When you use `ValueNotifier` to change port name, I'm not sure that `_internal` method will be called properly. Refer to #18 , instance recycling does not happen even if you delete this instance, so that init method will not be called.

If you have time, you can create a new instance of actual serial port name to test, without ValueNotifier. 

I will finish test later.

**Comment by Sunshine88888** [comment] 2023-06-02 18:21
Hi @FengChendian,
I have trimmed the code but still unable to read. I have tried with/without async too. I have added my further timmed code below.
![image](https://github.com/FengChendian/serial_port_win32/assets/34958458/9592b354-fe50-4709-93d7-07031e01ea1c)

After program is closed, I open Putty, it only shows "AT" command not those after it, seen in debug console.
![image](https://github.com/FengChendian/serial_port_win32/assets/34958458/0d1d8df3-f27e-432d-be09-76c3c52151b4)

```
// ignore_for_file: prefer_const_constructors
import 'package:flutter/material.dart';
import 'package:serial_port_win32/serial_port_win32.dart';

Future writeModemCommand(String command) async {
  final telitPort = SerialPort("COM9");
  // telitPort.open();
  print("Port Open: ${telitPort.isOpened}");
  print("Writing command: $command");
  try {
    telitPort.writeBytesFromString("$command\r");
    telitPort.readBytesOnListen(8, (value) async {
      String data = await String.fromCharCodes(value);
      print("${DateTime.now()} : $data");
      print(data);
    });
  } finally {}
}

void main() {
  runApp(const MyApp());
  print("Start");
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Modem App',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Telit Modem Status'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final txtATcommand = TextEditingController();

  void initState() {}

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Modem',
      home: Scaffold(
        appBar: AppBar(),
        body: Row(
          children: [
            Expanded(
              child: Column(
                children: [
                  Spacer(
                    flex: 1,
                  ),
                  TextField(
                    controller: txtATcommand,
                    decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      hintText: 'Enter AT command',
                    ),
                    onSubmitted: (value) => writeModemCommand(txtATcommand.text),
                  ),
                  Spacer(
                    flex: 1,
                  ),
                  ElevatedButton(
                    child: Text('Send AT'),
                    onPressed: () => {
                      // Replace with your desired modem command
                      writeModemCommand("AT"),
                    },
                  ),
                  Spacer(
                    flex: 1,
                  ),
                  ElevatedButton(
                    child: Text('Get Network Status'),
                    onPressed: () => {
                      // Replace with your desired modem command
                      writeModemCommand("AT+CREG?"),
                    },
                  ),
                  Spacer(
                    flex: 1,
                  ),
                  ElevatedButton(
                    child: Text('Get Phone No.'),
                    onPressed: () => {
                      // Replace with your desired modem command
                      writeModemCommand("AT+CNUM"),
                    },
                  ),
                  Spacer(
                    flex: 1,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by FengChendian** [comment] 2023-06-03 16:00
Strangely... I use virtual port and your code on my PC. I can send and receive data correctly.

1. Do you entirely close putty or other serial read software when use flutter? You said that `After program is closed, I open Putty, it only shows "AT" command not those after it, seen in debug console.` It looks like you are using putty to monitor port data.
2. What's your system version and flutter version? I test your code on windows 11.

I will test your code on ESP32 with AT firmware. But I think that some programs **truncated the data** before flutter get it.

![image](https://github.com/FengChendian/serial_port_win32/assets/37545115/500e5476-c020-4bfa-91aa-d1d0e6274bcc)
![image](https://github.com/FengChendian/serial_port_win32/assets/37545115/768a22ab-9607-40ef-b4dd-0fc71d3e0b64)
![image](https://github.com/FengChendian/serial_port_win32/assets/37545115/16174605-60a7-4411-b2ff-a64f0991c24d)

**Comment by Sunshine88888** [comment] 2023-06-04 07:42
@FengChendian , thank you for investigating. Good that the code works on your side. 

Putty is opened and closed only when the Flutter app is not running. I am unable to connect with Putty terminal when Flutter app is running, good to prove I am talking to same port. 

I have tried to isolate by find programs using the modem dll. 

I will try to find any other program/Windows which might be inteferring with the read of data. I might try rebuilding flutter.

**Comment by FengChendian** [comment] 2023-06-04 11:36
> @FengChendian , thank you for investigating. Good that the code works on your side.
> 
> Putty is opened and closed only when the Flutter app is not running. I am unable to connect with Putty terminal when Flutter app is running, good to prove I am talking to same port.
> 
> I have tried to isolate by find programs using the modem dll.
> 
> I will try to find any other program/Windows which might be inteferring with the read of data. I might try rebuilding flutter.

Some people also report bugs that cannot read data. There are also some who are able to read and write data correctly. Maybe it's due to different system/flutter version or hardware. But... I don't know.  If you can help to find the bug it is much appreciated

And this library depends on win32 package and FFI package. Error message can't be reached directly, although the code is based on Microsoft Serial Docs and translated from Microsoft C++ Example.

**Comment by FengChendian** [comment] 2023-06-05 03:26
> @FengChendian , thank you for investigating. Good that the code works on your side. 
> 
> Putty is opened and closed only when the Flutter app is not running. I am unable to connect with Putty terminal when Flutter app is running, good to prove I am talking to same port. 
> 
> I have tried to isolate by find programs using the modem dll. 
> 
> I will try to find any other program/Windows which might be inteferring with the read of data. I might try rebuilding flutter. 

By the way, can your modem process '/0' or '/n' terminator correctly? Maybe AT command has been sent, but 'AT/0', 'AT/0/n', 'AT/n' and 'AT' has different response.

**Comment by dasaintgray** [comment] 2023-06-22 00:58
> Have same issue too. I believe there is something blocking read from port. When running Putty, I can see the messages written and response by program. Did you find a solution @dasaintgray ?

I've change the other package library

**Comment by BluesCool** [comment] 2023-07-17 05:29
I also encountered this problem, it can be sent normally, but not received, I wrote the plug-in in a tool class.
code show as below：
```jsx：
import 'dart:typed_data';
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:serial_port_win32/serial_port_win32.dart';
import '../common/global.dart';

class WinSerialPortUtils {
  // static WinSerialPortUtils _instance;
  SerialPort? _serialPort;
  bool _settingBaudRate = false;
  // factory WinSerialPortUtils() => _instance ??= WinSerialPortUtils._();

  // WinSerialPortUtils._();

  // 单例对象
  static final WinSerialPortUtils _instance = WinSerialPortUtils._internal();

  // 工厂构造函数
  factory WinSerialPortUtils() => _instance;

  // 私有构造函数
  WinSerialPortUtils._internal();

   StreamController<List<String>> _receiveStreamController =
      StreamController<List<String>>.broadcast();

  // 获取数据接收流
  Stream<List<String>> get receiveStream => _receiveStreamController.stream;

  // 串口连接状态
  StreamController<bool> _connectStreamController =
      StreamController<bool>.broadcast();

  // 获取串口连接状态流
  Stream<bool> get connectStream => _connectStreamController.stream;

  void open(String portName) {
    // var ports = SerialPort.getAvailablePorts();
    _serialPort = SerialPort(portName, openNow: false);
      // _serialPort!.BaudRate = 115200;
      // _serialPort!.open();

      _serialPort!.openWithSettings(BaudRate: 115200);
      _connectStreamController.add(true);
      _serialPort!.readBytesOnListen(13, (data) async {
      for (int i = 0; i < data.length; i++) {
        String hexString = data[i].toRadixString(16).padLeft(2, '0');
        if ((hexString.toUpperCase().endsWith("AC") ||
                hexString.toUpperCase().endsWith("EE")) &&
            Global.serialPortMessage.length == 12) {
          // Global.messageHandledStatus = false;
          Global.serialPortMessage.clear();
        }
        Global.serialPortMessage.add(hexString);
        print('receivedHex: $hexString');
        if (Global.serialPortMessage.length == 12 &&
            hexString.toUpperCase().endsWith('FF')) {
          //通过流把数据传递出去
          _receiveStreamController.add(Global.serialPortMessage);
          Global.messageHandledStatus = false;
          // list.clear();
        }
      }
    });
  }

  void sendData(String sendData) {
    if (sendData.isEmpty || _serialPort == null) {
      return;
    }
    print('发送数据:$sendData');
    List<int> dataList = [];
    int len = sendData.length ~/ 2;
    for (int i = 0; i < len; i++) {
      String data = sendData.trim().substring(2 * i, 2 * (i + 1));
      int? d = _hexToInt2(data);
      dataList.add(d!);
    }
    // dataList.add(-86);
    // Uint8List data = Uint8List.fromList(sendData.codeUnits);

    // Logger.info('发送数据${dataList.toString()}');
    var bytes = Uint8List.fromList(dataList);
    _serialPort!.writeBytesFromUint8List(bytes);
  }

  int _hexToInt2(String hex) {
    int value = 0;
    for (int i = 0; i < hex.length; i++) {
      int hexDigit = hex.codeUnitAt(i);
      if (hexDigit >= 48 && hexDigit <= 57) {
        value = (value << 4) | (hexDigit - 48);
      } else if (hexDigit >= 65 && hexDigit <= 70) {
        value = (value << 4) | (hexDigit - 55);
      } else if (hexDigit >= 97 && hexDigit <= 102) {
        value = (value << 4) | (hexDigit - 87);
      } else {
        throw FormatException('非法的16进制字符');
      }
    }
    return value;
  }

  void readData() {
    _serialPort!.readBytesOnListen(12, (data) {
      for (int i = 0; i < data.length; i++) {
        String hexString = data[i].toRadixString(16).padLeft(2, '0');
        if ((hexString.toUpperCase().endsWith("AC") ||
                hexString.toUpperCase().endsWith("EE")) &&
            Global.serialPortMessage.length == 12) {
          // Global.messageHandledStatus = false;
          Global.serialPortMessage.clear();
        }
        Global.serialPortMessage.add(hexString);
        print('receivedHex: $hexString');
        if (Global.serialPortMessage.length == 12 &&
            hexString.toUpperCase().endsWith('FF')) {
          //通过流把数据传递出去
          _receiveStreamController.add(Global.serialPortMessage);
          Global.messageHandledStatus = false;
          // list.clear();
        }
      }
    });
  }

  void close() {
    if (_serialPort != null) {
      _serialPort!.close();
      _connectStreamController.add(false);
    }
  }
}

**Comment by FengChendian** [comment] 2023-07-17 15:24
> I also encountered this problem, it can be sent normally, but not received, I wrote the plug-in in a tool class. code show as below：
> 
> ```
> import 'dart:typed_data';
> import 'dart:async';
> import 'package:flutter/material.dart';
> import 'package:serial_port_win32/serial_port_win32.dart';
> import '../common/global.dart';
> 
> class WinSerialPortUtils {
>   // static WinSerialPortUtils _instance;
>   SerialPort? _serialPort;
>   bool _settingBaudRate = false;
>   // factory WinSerialPortUtils() => _instance ??= WinSerialPortUtils._();
> 
>   // WinSerialPortUtils._();
> 
>   // 单例对象
>   static final WinSerialPortUtils _instance = WinSerialPortUtils._internal();
> 
>   // 工厂构造函数
>   factory WinSerialPortUtils() => _instance;
> 
>   // 私有构造函数
>   WinSerialPortUtils._internal();
> 
>    StreamController<List<String>> _receiveStreamController =
>       StreamController<List<String>>.broadcast();
> 
>   // 获取数据接收流
>   Stream<List<String>> get receiveStream => _receiveStreamController.stream;
> 
>   // 串口连接状态
>   StreamController<bool> _connectStreamController =
>       StreamController<bool>.broadcast();
> 
>   // 获取串口连接状态流
>   Stream<bool> get connectStream => _connectStreamController.stream;
> 
>   void open(String portName) {
>     // var ports = SerialPort.getAvailablePorts();
>     _serialPort = SerialPort(portName, openNow: false);
>       // _serialPort!.BaudRate = 115200;
>       // _serialPort!.open();
> 
>       _serialPort!.openWithSettings(BaudRate: 115200);
>       _connectStreamController.add(true);
>       _serialPort!.readBytesOnListen(13, (data) async {
>       for (int i = 0; i < data.length; i++) {
>         String hexString = data[i].toRadixString(16).padLeft(2, '0');
>         if ((hexString.toUpperCase().endsWith("AC") ||
>                 hexString.toUpperCase().endsWith("EE")) &&
>             Global.serialPortMessage.length == 12) {
>           // Global.messageHandledStatus = false;
>           Global.serialPortMessage.clear();
>         }
>         Global.serialPortMessage.add(hexString);
>         print('receivedHex: $hexString');
>         if (Global.serialPortMessage.length == 12 &&
>             hexString.toUpperCase().endsWith('FF')) {
>           //通过流把数据传递出去
>           _receiveStreamController.add(Global.serialPortMessage);
>           Global.messageHandledStatus = false;
>           // list.clear();
>         }
>       }
>     });
>   }
> 
>   void sendData(String sendData) {
>     if (sendData.isEmpty || _serialPort == null) {
>       return;
>     }
>     print('发送数据:$sendData');
>     List<int> dataList = [];
>     int len = sendData.length ~/ 2;
>     for (int i = 0; i < len; i++) {
>       String data = sendData.trim().substring(2 * i, 2 * (i + 1));
>       int? d = _hexToInt2(data);
>       dataList.add(d!);
>     }
>     // dataList.add(-86);
>     // Uint8List data = Uint8List.fromList(sendData.codeUnits);
> 
>     // Logger.info('发送数据${dataList.toString()}');
>     var bytes = Uint8List.fromList(dataList);
>     _serialPort!.writeBytesFromUint8List(bytes);
>   }
> 
>   int _hexToInt2(String hex) {
>     int value = 0;
>     for (int i = 0; i < hex.length; i++) {
>       int hexDigit = hex.codeUnitAt(i);
>       if (hexDigit >= 48 && hexDigit <= 57) {
>         value = (value << 4) | (hexDigit - 48);
>       } else if (hexDigit >= 65 && hexDigit <= 70) {
>         value = (value << 4) | (hexDigit - 55);
>       } else if (hexDigit >= 97 && hexDigit <= 102) {
>         value = (value << 4) | (hexDigit - 87);
>       } else {
>         throw FormatException('非法的16进制字符');
>       }
>     }
>     return value;
>   }
> 
>   void readData() {
>     _serialPort!.readBytesOnListen(12, (data) {
>       for (int i = 0; i < data.length; i++) {
>         String hexString = data[i].toRadixString(16).padLeft(2, '0');
>         if ((hexString.toUpperCase().endsWith("AC") ||
>                 hexString.toUpperCase().endsWith("EE")) &&
>             Global.serialPortMessage.length == 12) {
>           // Global.messageHandledStatus = false;
>           Global.serialPortMessage.clear();
>         }
>         Global.serialPortMessage.add(hexString);
>         print('receivedHex: $hexString');
>         if (Global.serialPortMessage.length == 12 &&
>             hexString.toUpperCase().endsWith('FF')) {
>           //通过流把数据传递出去
>           _receiveStreamController.add(Global.serialPortMessage);
>           Global.messageHandledStatus = false;
>           // list.clear();
>         }
>       }
>     });
>   }
> 
>   void close() {
>     if (_serialPort != null) {
>       _serialPort!.close();
>       _connectStreamController.add(false);
>     }
>   }
> }
> ```

你的代码看起来应该没有问题，应该和之前的无法读取数据的bug是同一种，但没找到问题在哪，只知道基本都是出在AT指令和模块交互时，不知道是dartVM因为某种原因截断了消息导致size不匹配还是根本没收到。
你和什么设备通信？这个库的代码我用STM32的USB Device VCP和ESP32的USB CDC/JTAG接口以及虚拟串口服务在USB 2.0 FS模式下测试过，是没问题的，但AT指令之类的我没测试过。

**Comment by FengChendian** [comment] 2023-07-18 03:22
> 我的系统是win11，用的是2个PL2303芯片的USB串口

2303挺常用，看起来问题应该出在read函数或者依赖的win32库上。

能否再问点详细的问题
1. 您涉及到的通信指令有哪些（包括换行符，终止符之类的），我这边模拟一下看看
2. 您那边可以帮我尝试一下：以非监听的方式，阻塞使用readbytesonce函数读取数据，看看能否读取？

**Comment by dasaintgray** [comment] 2023-07-18 05:14
> Have same issue too. I believe there is something blocking read from port. When running Putty, I can see the messages written and response by program. Did you find a solution @dasaintgray ?

HI, I already change the package.

**Comment by FengChendian** [comment] 2023-08-28 14:09
I confirm that `ClearCommError` causes the read bug. `ClearCommError` will return 1 (CE_RXOVER) in some systems. So `cbInQue` is wrong.

**Comment by FengChendian** [comment] 2023-08-29 07:11
This bug should be fixed when I remove the `PurgeComm` function before read after version `1.1.0`.

 And I create a read bug collection #27 in issues. If bug persists, please submit it in #27 .

**Closed by FengChendian** 2023-08-29 07:11 UTC
